### ISSUE TITLE
Feature Request: Copy as wiki link and copy as BBCode

### ISSUE THREAD

**Issue by pepoluan** [nhoyt/copy-page-link#2]
Hi! I maintain several wiki, and it would be a great boon if, in addition to the current supported formats, you can add the following:

* Copy as wiki link: `[<url> <title>]`
* Copy as BBCode: `[url=<url>]<title>[/url]`

**Comment by nhoyt** [comment]
Hello! I've added the two formats you requested as part of Copy Page Link v2.4. I named the wiki format 'MediaWiki', as there are numerous wiki formats for links and MediaWiki seems to be one of the most widely used matching the format you specified. Let me know if you encounter any issues, and thanks for using Copy Page Link.

**Comment by nhoyt** [comment]
v3.0.0 includes MediaWiki format
