### ISSUE TITLE
Feature request: ease format specification (integrate with context menu?)

### ISSUE THREAD

**Issue by Wolf-SO** [nhoyt/copy-page-link#3]
The format preselection via configuration is a real showstopper: I'm constantly switching between MediaWiki and Markdown, so the configuration doesn't add any help from my POV.

If this decision could be delegated to a submenu, ideally in the context menu, I'd switch to this add-on from [url2clipboard](https://github.com/asamuzaK/url2clipboard) because it obviously requires [too many permissions](https://addons.mozilla.org/de/firefox/addon/url2clipboard/reviews/1740070/).

**Comment by nhoyt** [comment]
v3.0.0 has moved the format selection from the extension options to the popup menu.
